api_login_check:
    path: /api/login_check
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
editUser:
    path: '/api/user/edit'
    methods: ['PUT', 'PATCH']
    controller: 'App\Controller\UserController::editUser'

logout:
    path: '/api/user/logout'
    methods: ['POST']
    controller: 'App\Controller\UserController::logout'
